name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Godot
        uses: chickenbellyfin/action-godot@v1
        with:
          version: 4.6.1
      - name: Build APK
        run: |
          mkdir -p build
          godot --export-release Android ./build/app.apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: TelegramBypass
          path: build/app.apk
